//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRM_delivery_header
    {
        public int id { get; set; }
        public string SN { get; set; }
        public int dYear { get; set; }
        public int dSN { get; set; }
        public int customer_id { get; set; }
        public string address { get; set; }
        public int contract_header_id { get; set; }
        public System.DateTime delivery_date { get; set; }
        public Nullable<int> delivery_user_id { get; set; }
        public byte status { get; set; }
        public string remark { get; set; }
        public System.DateTime created_time { get; set; }
        public bool delete_flag { get; set; }
    }
}
