//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRM_delivery_detail
    {
        public int id { get; set; }
        public int header_id { get; set; }
        public int contract_detail_id { get; set; }
        public int qty { get; set; }
        public string remark { get; set; }
        public Nullable<int> attach_label_id { get; set; }
        public int status { get; set; }
        public bool delete_flag { get; set; }
        public Nullable<System.DateTime> DeliverTime { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<bool> CW_checked { get; set; }
        public Nullable<bool> CZ_checked { get; set; }
        public Nullable<System.DateTime> CW_checked_Time { get; set; }
        public Nullable<System.DateTime> CZ_checked_Time { get; set; }
    
        public virtual CRM_contract_detail CRM_contract_detail { get; set; }
        public virtual CRM_contract_header CRM_contract_header { get; set; }
    }
}
