//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class DY_CRM_customers
    {
        public int Id { get; set; }
        public string SN { get; set; }
        public string Name { get; set; }
        public string Name_E { get; set; }
        public string ShortName { get; set; }
        public string ShortName_E { get; set; }
        public string Address { get; set; }
        public string Address_delivery { get; set; }
        public string zipcode { get; set; }
        public string linkman { get; set; }
        public string tel { get; set; }
        public string email { get; set; }
        public string remark { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<bool> State { get; set; }
        public string ListUserId { get; set; }
    }
}
