//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class ehr_post
    {
        public long id { get; set; }
        public string number { get; set; }
        public string name { get; set; }
        public long employee { get; set; }
        public System.DateTime time { get; set; }
        public int department { get; set; }
        public string departmentname { get; set; }
        public string hard { get; set; }
        public string hardname { get; set; }
        public Nullable<short> complement { get; set; }
        public string complementuser { get; set; }
        public string complementname { get; set; }
        public string complementmark { get; set; }
        public System.DateTime acttime { get; set; }
        public Nullable<short> way { get; set; }
        public string photo { get; set; }
        public Nullable<short> hardtype { get; set; }
        public Nullable<short> inout { get; set; }
    }
}
