//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_jobs
    {
        public int id { get; set; }
        public string jobs { get; set; }
        public int user_id { get; set; }
        public string name { get; set; }
        public string useranme { get; set; }
        public string department { get; set; }
        public System.DateTime created_time { get; set; }
        public long delete_flag { get; set; }
        public string position { get; set; }
        public string password { get; set; }
        public Nullable<int> type { get; set; }
    }
}
