//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class INV_accessory_type
    {
        public INV_accessory_type()
        {
            this.INV_accessory_stock = new HashSet<INV_accessory_stock>();
            this.INV_accessory_purchase_order = new HashSet<INV_accessory_purchase_order>();
        }
    
        public int Id { get; set; }
        public string name { get; set; }
        public string unit { get; set; }
        public System.DateTime created_time { get; set; }
        public string remark { get; set; }
        public bool delete_flag { get; set; }
        public Nullable<int> catalog_id { get; set; }
    
        public virtual ICollection<INV_accessory_stock> INV_accessory_stock { get; set; }
        public virtual ICollection<INV_accessory_purchase_order> INV_accessory_purchase_order { get; set; }
        public virtual INV_accessory_catalog INV_accessory_catalog { get; set; }
    }
}
