//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class INV_inventories
    {
        public INV_inventories()
        {
            this.INV_accessory_stock = new HashSet<INV_accessory_stock>();
            this.INV_material_stock = new HashSet<INV_material_stock>();
            this.INV_materials = new HashSet<INV_materials>();
            this.INV_single_board = new HashSet<INV_single_board>();
            this.INV_semi = new HashSet<INV_semi>();
            this.INV_labels = new HashSet<INV_labels>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public byte type { get; set; }
        public string address { get; set; }
        public string remark { get; set; }
        public System.DateTime created_time { get; set; }
        public bool delete_flag { get; set; }
    
        public virtual ICollection<INV_accessory_stock> INV_accessory_stock { get; set; }
        public virtual ICollection<INV_material_stock> INV_material_stock { get; set; }
        public virtual ICollection<INV_materials> INV_materials { get; set; }
        public virtual ICollection<INV_single_board> INV_single_board { get; set; }
        public virtual ICollection<INV_semi> INV_semi { get; set; }
        public virtual ICollection<INV_labels> INV_labels { get; set; }
    }
}
