//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class INV_accessory
    {
        public int id { get; set; }
        public int wood_id { get; set; }
        public int inv_id { get; set; }
        public decimal qty { get; set; }
        public int in_out { get; set; }
        public Nullable<System.DateTime> event_date { get; set; }
        public string remark { get; set; }
        public Nullable<int> user_id { get; set; }
        public string user_name { get; set; }
        public System.DateTime created_time { get; set; }
        public bool delete_flag { get; set; }
        public Nullable<int> type { get; set; }
        public Nullable<int> PO_id { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<int> event_user_id { get; set; }
    }
}
