//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class INV_accessory_purchase_order
    {
        public int id { get; set; }
        public string SN { get; set; }
        public int apply_user_id { get; set; }
        public string apply_user_name { get; set; }
        public string apply_user_department { get; set; }
        public Nullable<System.DateTime> require_date { get; set; }
        public int accessory_id { get; set; }
        public Nullable<decimal> qty { get; set; }
        public string unit { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<int> supplier_id { get; set; }
        public string require_remark { get; set; }
        public string paper_number { get; set; }
        public string paper_img { get; set; }
        public Nullable<System.DateTime> purchase_date { get; set; }
        public Nullable<int> purchase_qty { get; set; }
        public string remark { get; set; }
        public int status { get; set; }
        public Nullable<int> check_user_id { get; set; }
        public string check_user_name { get; set; }
        public Nullable<System.DateTime> checked_date { get; set; }
        public Nullable<int> input_user_id { get; set; }
        public string input_user_name { get; set; }
        public int FR_flag { get; set; }
        public System.DateTime created_time { get; set; }
        public bool delete_flag { get; set; }
    
        public virtual INV_accessory_type INV_accessory_type { get; set; }
        public virtual CRM_suppliers CRM_suppliers { get; set; }
    }
}
