//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class INV_purchase_order
    {
        public int id { get; set; }
        public string SN { get; set; }
        public int apply_user_id { get; set; }
        public string apply_user_name { get; set; }
        public string apply_user_department { get; set; }
        public Nullable<System.DateTime> require_date { get; set; }
        public int material_id { get; set; }
        public int qty { get; set; }
        public Nullable<byte> status { get; set; }
        public Nullable<int> check_user_id { get; set; }
        public string check_user_name { get; set; }
        public Nullable<System.DateTime> checked_date { get; set; }
        public Nullable<System.DateTime> purchase_date { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<int> purchase_qty { get; set; }
        public string remark { get; set; }
        public System.DateTime created_time { get; set; }
        public bool delete_flag { get; set; }
    }
}
