//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleService_Products
    {
        public System.Guid Id { get; set; }
        public Nullable<int> SaleServiceId { get; set; }
        public string ProductStyle { get; set; }
        public string ProductName { get; set; }
        public string WoodName { get; set; }
        public string QusState { get; set; }
        public string AnState { get; set; }
        public string Remark { get; set; }
        public Nullable<bool> DelState { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
    
        public virtual SaleServiceInfo SaleServiceInfo { get; set; }
    }
}
