//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleServiceInfo
    {
        public SaleServiceInfo()
        {
            this.SaleService_Products = new HashSet<SaleService_Products>();
        }
    
        public int Id { get; set; }
        public string SN { get; set; }
        public string Customer { get; set; }
        public string TelPhone { get; set; }
        public Nullable<System.DateTime> GoHomeDate { get; set; }
        public Nullable<System.DateTime> SaleSerDate { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string SFState { get; set; }
        public string LinkAddress { get; set; }
        public string userName { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<System.DateTime> CheckedTime { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<bool> DelState { get; set; }
        public string Remark { get; set; }
    
        public virtual ICollection<SaleService_Products> SaleService_Products { get; set; }
    }
}
