//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_notices
    {
        public int id { get; set; }
        public int user_id { get; set; }
        public Nullable<int> type { get; set; }
        public string Tname { get; set; }
        public Nullable<int> TID { get; set; }
        public string title { get; set; }
        public string summary { get; set; }
        public Nullable<int> post_id { get; set; }
        public string post_name { get; set; }
        public Nullable<int> checker_id { get; set; }
        public string checker_name { get; set; }
        public byte status { get; set; }
        public System.DateTime created_time { get; set; }
        public bool delete_flag { get; set; }
        public Nullable<int> reserved1 { get; set; }
        public Nullable<int> reserved2 { get; set; }
        public Nullable<int> reserved3 { get; set; }
        public string reserved4 { get; set; }
        public string reserved5 { get; set; }
    }
}
