//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class WIP_contract
    {
        public WIP_contract()
        {
            this.WIP_workorder = new HashSet<WIP_workorder>();
        }
    
        public int id { get; set; }
        public int product_id { get; set; }
        public int wood_id { get; set; }
        public string color { get; set; }
        public Nullable<bool> custom_flag { get; set; }
        public Nullable<int> length { get; set; }
        public Nullable<int> width { get; set; }
        public Nullable<int> height { get; set; }
        public System.DateTime created_time { get; set; }
        public bool delete_flag { get; set; }
        public Nullable<int> qty { get; set; }
    
        public virtual ICollection<WIP_workorder> WIP_workorder { get; set; }
        public virtual SYS_product SYS_product { get; set; }
        public virtual INV_wood_type INV_wood_type { get; set; }
    }
}
