//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class WIP_wo_events
    {
        public System.Guid id { get; set; }
        public int wo_id { get; set; }
        public Nullable<int> SN { get; set; }
        public string name { get; set; }
        public Nullable<int> user_id { get; set; }
        public string user_name { get; set; }
        public string event_log { get; set; }
        public string remark { get; set; }
        public System.DateTime created_time { get; set; }
        public bool delete_flag { get; set; }
    }
}
