//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class WIP_WO_salary
    {
        public int id { get; set; }
        public int user_id { get; set; }
        public string user_name { get; set; }
        public decimal price { get; set; }
        public int qty { get; set; }
        public decimal amount { get; set; }
        public int wo_id { get; set; }
        public string SN { get; set; }
        public Nullable<int> check_user_id { get; set; }
        public string check_user_name { get; set; }
        public byte status { get; set; }
        public System.DateTime created_time { get; set; }
        public bool delete_flag { get; set; }
    }
}
