//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class WIP_work_CW
    {
        public int Id { get; set; }
        public string workorder { get; set; }
        public Nullable<int> CRM_contract_detail_id { get; set; }
        public Nullable<int> WIP_contract_id { get; set; }
        public Nullable<int> qty { get; set; }
        public Nullable<int> product_id { get; set; }
        public string stye { get; set; }
        public string WoodName { get; set; }
        public string unit { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<int> GMqty { get; set; }
        public Nullable<int> YQqty { get; set; }
    
        public virtual SYS_product SYS_product { get; set; }
    }
}
