//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class XNERPEntities : DbContext
    {
        public XNERPEntities()
            : base("name=XNERPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CRM_contract_detail> CRM_contract_detail { get; set; }
        public DbSet<CRM_customers> CRM_customers { get; set; }
        public DbSet<HR_jobs> HR_jobs { get; set; }
        public DbSet<INV_accessory_PO_input> INV_accessory_PO_input { get; set; }
        public DbSet<INV_accessory_PO_output> INV_accessory_PO_output { get; set; }
        public DbSet<INV_accessory_stock> INV_accessory_stock { get; set; }
        public DbSet<INV_accessory_type> INV_accessory_type { get; set; }
        public DbSet<INV_inventories> INV_inventories { get; set; }
        public DbSet<INV_material_stock> INV_material_stock { get; set; }
        public DbSet<INV_materials> INV_materials { get; set; }
        public DbSet<INV_PO_input> INV_PO_input { get; set; }
        public DbSet<INV_PO_output> INV_PO_output { get; set; }
        public DbSet<INV_purchase_order> INV_purchase_order { get; set; }
        public DbSet<INV_single_board> INV_single_board { get; set; }
        public DbSet<INV_wood_type> INV_wood_type { get; set; }
        public DbSet<SYS_colors> SYS_colors { get; set; }
        public DbSet<SYS_company> SYS_company { get; set; }
        public DbSet<SYS_notices> SYS_notices { get; set; }
        public DbSet<SYS_product_SN> SYS_product_SN { get; set; }
        public DbSet<UserLogs> UserLogs { get; set; }
        public DbSet<WIP_wo_events> WIP_wo_events { get; set; }
        public DbSet<WIP_wo_wood> WIP_wo_wood { get; set; }
        public DbSet<WIP_workorder> WIP_workorder { get; set; }
        public DbSet<HR_salary_info> HR_salary_info { get; set; }
        public DbSet<INV_accessory> INV_accessory { get; set; }
        public DbSet<INV_accessory_catalog> INV_accessory_catalog { get; set; }
        public DbSet<SYS_product_area> SYS_product_area { get; set; }
        public DbSet<INV_inventory_type> INV_inventory_type { get; set; }
        public DbSet<XT_RM> XT_RM { get; set; }
        public DbSet<SYS_product> SYS_product { get; set; }
        public DbSet<CRM_contract_header> CRM_contract_header { get; set; }
        public DbSet<INV_accessory_purchase_order> INV_accessory_purchase_order { get; set; }
        public DbSet<CRM_suppliers> CRM_suppliers { get; set; }
        public DbSet<INV_semi> INV_semi { get; set; }
        public DbSet<WIP_contract> WIP_contract { get; set; }
        public DbSet<WIP_workflow> WIP_workflow { get; set; }
        public DbSet<WIP_WO_salary> WIP_WO_salary { get; set; }
        public DbSet<INV_labels> INV_labels { get; set; }
        public DbSet<CRM_delivery_tmp_header> CRM_delivery_tmp_header { get; set; }
        public DbSet<WIP_work_CW> WIP_work_CW { get; set; }
    }
}
